[build]
publish = "dist/public"
command = "./build.sh"

[context.production.environment]
HUGO_VERSION = "0.59.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1.environment]
HUGO_VERSION = "0.59.0"
HUGO_ENV = "production"

[context.deploy-preview.environment]
HUGO_VERSION = "0.59.0"

[context.branch-deploy.environment]
HUGO_VERSION = "0.59.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/latest/*"
  to = "/docs/:splat"
  force = true

[[redirects]]
  from = "/0.2.1/*"
  to = "/docs/:splat"
  force = true

[[redirects]]
  from = "/0.3.0/*"
  to = "/docs/:splat"
  force = true

[[redirects]]
  from = "/0.4.0/*"
  to = "/docs/:splat"
  force = true

[[redirects]]
  from = "/0.5.0/*"
  to = "/docs/:splat"
  force = true

[[redirects]]
  from = "/0.6.0/*"
  to = "/docs/:splat"
  force = true

[[redirects]]
  from = "/0.6.1/*"
  to = "/docs/:splat"
  force = true

[[redirects]]
  from = "/0.7.0/*"
  to = "/docs/:splat"
  force = true

[[redirects]]
  from = "/0.7.1/*"
  to = "/docs/:splat"
  force = true

[[redirects]]
  from = "/0.7.2/*"
  to = "/docs/:splat"
  force = true

[[redirects]]
  from = "/0.8.0/*"
  to = "/docs/:splat"
  force = true

[[redirects]]
  from = "/0.9.0/*"
  to = "/docs/:splat"
  force = true

[[redirects]]
  from = "/0.9.1/*"
  to = "/docs/:splat"
  force = true

[[redirects]]
  from = "/0.9.2/*"
  to = "/docs/:splat"
  force = true

[[redirects]]
  from = "/0.10.0/*"
  to = "/docs/:splat"
  force = true

[[redirects]]
  from = "/0.11.0/*"
  to = "/docs/:splat"
  force = true

[[redirects]]
  from = "/0.12.0/*"
  to = "/docs/:splat"
  force = true

[[redirects]]
  from = "/1.0-rc1/*"
  to = "/docs/:splat"
  force = true

[[redirects]]
  from = "/installation/installation"
  to = "/docs/installation"
  force = true

[[redirects]]
  from = "/"
  to = "/docs/"
  force = true
