baseURL = "https://docs.fission.io/0.12.0"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Fission: Serverless Functions for Kubernetes"
theme = "hugo-theme-docdock"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/fission/docs.fission.io/edit/master/docs/content/"
  description = "Documentation for Fission"
  author = "Fission"
  showVisitedLinks = false
  themeVariant = "fission"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Serverless Functions for Kubernetes"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]] 
name = "<i class='fa fa-fw fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/fission/fission"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-fw fa-bullhorn'></i> Credits"
url = "https://github.com/fission/fission/graphs/contributors"
weight = 11

staticDir = ["static"]
